package org.study.hydrowarehouse.dao;

import org.study.hydrowarehouse.entity.ProductSkuStatus;
import org.study.hydrowarehouse.exception.CoreException;

import java.util.List;
import java.util.Optional;

/**
 * Data Access Object (DAO) interface for {@link ProductSkuStatus} entities.
 * <p>
 * Provides methods to perform CRUD operations and queries related to product sku statuses.
 *
 * @author Aliaksandr Pishchala
 */
public interface ProductSkuStatusDao {

    /**
     * Persists the given {@link ProductSkuStatus} entity to the database.
     * <p>
     * If the entity is new (i.e., has no ID), it will be inserted and the generated ID will be returned.
     * If the entity already exists, behavior depends on implementation (it may result in an update or exception).
     * </p>
     *
     * @param skuStatus the {@link ProductSkuStatus} entity to be saved; must not be {@code null}
     * @return the ID of the saved entity (usually auto-generated by the database)
     * @throws CoreException if the save operation fails due to validation issues, persistence errors, or other unexpected conditions
     */
    int save(ProductSkuStatus skuStatus) throws CoreException;
    /**
     * Updates the given {@link ProductSkuStatus} entity in the database.
     * <p>
     * The entity must already exist; otherwise, the operation may fail or result in no changes.
     * </p>
     *
     * @param skuStatus the {@link ProductSkuStatus} entity to be updated; must not be {@code null}
     * @return {@code true} if the update was successful; {@code false} if the entity was not found or not updated
     * @throws CoreException if the update operation fails due to validation errors, concurrent modifications,
     *                       or persistence issues
     */
    boolean update(ProductSkuStatus skuStatus) throws CoreException;

    /**
     * Removes the {@link ProductSkuStatus} entity identified by the given ID from the database.
     *
     * @param id the ID of the status entity to remove; must not be {@code null}
     * @return {@code true} if the entity was successfully removed; {@code false} if the entity was not found
     * @throws CoreException if the remove operation fails due to referential constraints, data integrity issues,
     *                       or other unexpected conditions
     */
    boolean remove(Integer id) throws CoreException;

    /**
     * Retrieves all {@link ProductSkuStatus} entities from the database.
     *
     * @return a list containing all existing {@link ProductSkuStatus} records; never {@code null}, but may be empty
     * @throws CoreException if an error occurs while accessing the data source
     */
    List<ProductSkuStatus> findAll() throws CoreException;

    /**
     * Finds a {@link ProductSkuStatus} entity by its status name.
     *
     * @param status the name of the status to search for; must not be {@code null} or blank
     * @return an {@link Optional} containing the found entity, or {@link Optional#empty()} if no match is found
     * @throws CoreException if an error occurs while accessing the data source or processing the request
     */
    Optional<ProductSkuStatus> findByStatus(String status) throws CoreException;

    /**
     * Finds a {@link ProductSkuStatus} entity by its unique identifier.
     *
     * @param statusId the ID of the status entity to retrieve; must not be {@code null}
     * @return an {@link Optional} containing the found entity, or {@link Optional#empty()} if no entity is found
     * @throws CoreException if an error occurs while accessing the data source
     */
    Optional<ProductSkuStatus> findById(Integer statusId) throws CoreException;
}
