package org.study.hydrowarehouse.dao;

import org.study.hydrowarehouse.entity.Product;
import org.study.hydrowarehouse.entity.ProductSku;
import org.study.hydrowarehouse.entity.ProductSkuStatus;
import org.study.hydrowarehouse.exception.CoreException;

import java.util.List;
import java.util.Optional;

/**
 * Interface {@link ProductSkuDao} provides operation with data of database table 'productSku'.
 *
 * @author Aliaksandr Pishchala
 */
public interface ProductSkuDao {

    /**
     * Persists the given {@link ProductSku} entity to the database.
     * <p>
     * If the entity is new (i.e., has no ID), it will be inserted and the generated ID will be returned.
     * If the entity already exists, an update may be performed depending on the implementation.
     * </p>
     *
     * @param productSku the ProductSku entity to be saved; must not be {@code null}
     * @return the ID of the saved entity (usually auto-generated by the database)
     * @throws CoreException if the save operation fails due to validation issues, database errors, or other unexpected conditions
     */
    int save(ProductSku productSku) throws CoreException;

    /**
     * Updates the existing {@link ProductSku} entity in the database.
     * <p>
     * The entity must already exist (typically identified by a non-null ID).
     * </p>
     *
     * @param productSku the ProductSku entity containing updated data; must not be {@code null}
     * @return {@code true} if the update was successful, {@code false} if the entity was not found or update failed
     * @throws CoreException if a data access error occurs or if validation fails
     */
    boolean update(ProductSku productSku) throws CoreException;

    /**
     * Removes the {@link ProductSku} entity with the specified ID from the database.
     *
     * @param id the unique identifier of the ProductSku to be removed; must not be {@code null}
     * @return {@code true} if the entity was successfully removed, {@code false} if no such entity exists
     * @throws CoreException if a data access error occurs during deletion
     */
    boolean remove(Integer id) throws CoreException;

    /**
     * Retrieves a ProductSku by its unique identifier.
     *
     * @param id the ID of the ProductSku to retrieve
     * @return an Optional containing the ProductSku if found, or empty if not found
     * @throws CoreException if a data access or processing error occurs
     */
    Optional<ProductSku> findById(Integer id) throws CoreException;

    /**
     * Retrieves all ProductSkus that match the given SKU code.
     *
     * @param code the SKU code to search for
     * @return a list of ProductSkus matching the provided code
     * @throws CoreException if a data access or processing error occurs
     */
    List<ProductSku> findByCode(String code) throws CoreException;

    /**
     * Retrieves a paginated list of ProductSkus with the specified status.
     *
     * @param limit the maximum number of results to return
     * @param offset the offset from which to start returning results
     * @param status the status of the ProductSkus to filter by
     * @return a list of ProductSkus with the given status
     * @throws CoreException if a data access or processing error occurs
     */
    List<ProductSku> findAllByStatus(int limit, int offset, ProductSkuStatus status) throws CoreException;

    /**
     * Retrieves a paginated list of ProductSkus associated with a specific product.
     *
     * @param limit the maximum number of results to return
     * @param offset the offset from which to start returning results
     * @param product the product entity to filter SKUs by
     * @return a list of ProductSkus associated with the given product
     * @throws CoreException if a data access or processing error occurs
     */
    List<ProductSku> findAllByProduct(int limit, int offset, Product product) throws CoreException;
}
