spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/hydro-company?useUnicode=true?serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/hydro-user-company?useUnicode=true?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.hikari.maximum-pool-size=7
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

hibernate.dialect=org.hibernate.dialect.MySQLDialect
#hibernate.hbm2ddl.auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=990000000

spring.timezone=UTC

file.upload-user-dir=uploads/user_dir/
file.upload-product-scheme-dir=uploads/product/scheme/
file.upload-product-images-dir=uploads/product/images/

file.upload-test-dir=uploads/test/test/test/
file.multipart.max-size-file=3145728
file.multipart.max-length-file=254
file.multipart.max-allowed-files=5

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=15MB